server:
  port: 4000

app:
  jwt:
    secret: "change-me-change-me-change-me-change-me"
    expiration-ms: 604800000
  uploads-dir: "${user.dir}/uploads"

spring:
  datasource:
    url: jdbc:postgresql://guvi_lms_userdb_user:nUlCrSw8mRmUtqIlAufEHblEZLyVLs2c@dpg-d5p5tsjvbchc738tt3hg-a.oregon-postgres.render.com/guvi_lms_userdb
    username: guvi_lms_userdb_user
    password: nUlCrSw8mRmUtqIlAufEHblEZLyVLs2c
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

springdoc:
  api-docs:
    path: /api/docs
  swagger-ui:
    path: /api/docs/ui
